[Service]
ExecStartPre=-/bin/sh -c 'c=0; while [ "$(getprop init.svc.vendor.audio-hal)" != "running" ] && [ $c -lt 90 ]; do sleep 1; c=$((c+1)); done'
ExecStart=
ExecStart=/usr/bin/env -u HYBRIS_USE_VENDOR_NAMESPACE /usr/bin/pulseaudio --daemonize=no --log-target=journal
