[Service]
ExecStartPre=/bin/sh -c 'c=0; while [ ! -e /sys/class/backlight/panel0-backlight/brightness ] && [ $$c -lt 60 ]; do sleep 0.5; c=$$((c+1)); done'
ExecStartPre=-/bin/sh -c 'mkdir -p /run/empty; mountpoint -q /sys/class/backlight/panel || mount --bind /run/empty /sys/class/backlight/panel'
